import Vue from 'vue';
import { sortNumValuesAgGrid } from '~/assets/js/utils/helpers';
import { currencyFormatter } from '~/components/pages/analytics/brand/helpers/currencyFormatter';
import { numberFormatter } from '~/components/pages/analytics/brand/helpers/numberFormatter';
// import { tooltipFormatter } from '~/components/pages/analytics/brand/helpers/tooltipFormatter';
import LinkToCategoriesRenderer from '~/components/pages/analytics/brand/additional/LinkToCategoriesRenderer';

const colors = ['#FC6E90', '#F4E450', '#5DDC98'];
/* eslint-disable */

export const productsHeaderNames = [
    {
        field: 'sku',
        headerName: 'Артикул',
        headerTooltip: 'Артикул',
        order: 1,
        filter: 'agTextColumnFilter',
        cellRenderer: params =>
            `<a class="tabs-product__table-link" href="${params.data.url}" target="_blank">${params.data.sku}</a>`,
    },
    {
        field: 'image_middle',
        headerName: 'Фото',
        headerTooltip: 'Фото',
        order: 0,
        maxWidth: 80,
        cellRenderer: params =>
            `<div style="height: 100%; display: flex; align-items: center;">
                <img src="${params.value}" style="width: 32px; height: 32px; object-fit: contain"/>
            </div>`,
        // tooltipValueGetter: params => tooltipFormatter(params),
        autoSize: false,
    },
    {
        field: 'name',
        headerName: 'Название',
        headerTooltip: 'Название',
        order: 1,
        sortable: true,
        filter: 'agTextColumnFilter',
        autoSize: false,
    },
    {
        field: 'subject',
        headerName: 'Предмет',
        headerTooltip: 'Предмет',
        order: 2,
        sortable: true,
        filter: 'agTextColumnFilter',
        autoSize: false,
    },
    {
        field: 'revenue',
        headerName: 'Выручка',
        headerTooltip: 'Выручка',
        order: 3,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: false,
    },
    {
        field: 'position',
        headerName: 'Позиция',
        headerTooltip: 'Позиция',
        order: 4,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => (params.value === 0 ? '-' : numberFormatter(params.value)),
        autoSize: true,
    },
    {
        field: 'brand',
        headerName: 'Бренд',
        headerTooltip: 'Бренд',
        order: 5,
        hide: true,
        autoSize: false,
    },
    {
        field: 'category',
        headerName: 'Подкатегории',
        headerTooltip: 'Подкатегории',
        order: 8,
        sortable: true,
        filter: 'agTextColumnFilter',
        cellRendererFramework: Vue.extend(LinkToCategoriesRenderer),
        // tooltipValueGetter: params => tooltipFormatter(params),
        autoSize: false,
    },
    {
        field: 'supplier',
        headerName: 'Продавец',
        headerTooltip: 'Продавец',
        order: 8,
        sortable: true,
        filter: 'agTextColumnFilter',
        // tooltipValueGetter: params => tooltipFormatter(params),
        autoSize: false,
    },
    {
        field: 'stock',
        headerName: 'Остаток',
        headerTooltip: 'Остаток',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.data.stock),
        autoSize: true,
    },
    {
        field: 'comments',
        headerName: 'Комментарии',
        headerTooltip: 'Комментарии',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.data.comments),
        autoSize: true,
    },
    {
        field: 'rating',
        headerName: 'Рейтинг',
        headerTooltip: 'Рейтинг',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        autoSize: true,
    },
    {
        field: 'last_price',
        headerName: 'Цена',
        headerTooltip: 'Цена',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: false,
    },
    {
        field: 'days_in_stock',
        headerName: 'Кол-во дней в наличии',
        headerTooltip: 'Кол-во дней в наличии',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        autoSize: true,
    },
    {
        field: 'total_sales',
        headerName: 'Продажи',
        headerTooltip: 'Продажи',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'graph_sales',
        headerName: 'График продаж',
        headerTooltip: 'График продаж',
        order: 8,
        hide: true,
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
            sparklineOptions: {
                type: 'column',
                fill: colors[2],
                highlightStyle: {
                    fill: colors[2],
                },
                axis: {
                    strokeWidth: 0,
                },
            },
        },
        autoSize: false,
    },
    {
        field: 'color',
        headerName: 'Цвет',
        headerTooltip: 'Цвет',
        sortable: true,
        order: 9,
        filter: 'agTextColumnFilter',
        autoSize: true,
    },
    {
        field: 'graph_price',
        headerName: 'Изменение цены',
        headerTooltip: 'Изменение цены',
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
            sparklineOptions: {
                type: 'column',
                fill: colors[2],
                highlightStyle: {
                    fill: colors[2],
                },
                axis: {
                    strokeWidth: 0,
                },
            },
        },
    },
    {
        field: 'graph_price',
        headerName: 'Изменение цены',
        headerTooltip: 'Изменение цены',
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
            sparklineOptions: {
                type: 'column',
                fill: colors[2],
                highlightStyle: {
                    fill: colors[2],
                },
                axis: {
                    strokeWidth: 0,
                },
            },
        },
    },
    {
        field: 'graph_category_count',
        headerName: 'Число категорий',
        headerTooltip: 'Число категорий',
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
            sparklineOptions: {
                type: 'column',
                fill: colors[2],
                highlightStyle: {
                    fill: colors[2],
                },
                axis: {
                    strokeWidth: 0,
                },
            },
        },
    },

    {
        field: 'graph_stock',
        headerName: 'График остатков',
        headerTooltip: 'График остатков',
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
            sparklineOptions: {
                type: 'column',
                fill: colors[2],
                highlightStyle: {
                    fill: colors[2],
                },
                axis: {
                    strokeWidth: 0,
                },
            },
        },
    },
];

export const categoriesHeaderNames = [
    {
        field: 'category',
        headerName: 'Категория',
        headerTooltip: 'Категория',
        sortable: true,
        filter: 'agTextColumnFilter',
        cellRendererFramework: Vue.extend(LinkToCategoriesRenderer),
        // tooltipValueGetter: params => tooltipFormatter(params),
        autoSize: false,
    },
    {
        field: 'revenue',
        headerName: 'Выручка',
        headerTooltip: 'Выручка',
        order: 6,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
    {
        field: 'avg_rating',
        headerName: 'Средний рейтинг',
        headerTooltip: 'Средний рейтинг',
        sortable: true,
        filter: 'agNumberColumnFilter',
        autoSize: true,
    },
    {
        field: 'avg_comments',
        headerName: 'Комментарии',
        headerTooltip: 'Комментарии',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'products',
        headerName: 'Товаров',
        headerTooltip: 'Товаров',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'products_with_sales',
        headerName: 'Товаров с продажами',
        headerTooltip: 'Товаров с продажами',
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
    },
    {
        field: 'sales',
        headerName: 'Продажи',
        headerTooltip: 'Продажи',
        sortable: true,
        filter: 'agNumberColumnFilter',
        comparator: sortNumValuesAgGrid,
        valueFormatter: params => numberFormatter(params.value),
    },
    {
        field: 'avg_price',
        headerName: 'Средняя цена',
        headerTooltip: 'Средняя цена',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
    {
        field: 'subject',
        headerName: 'Предмет',
        headerTooltip: 'Предмет',
        sortable: true,
        filter: 'agTextColumnFilter',
        // tooltipValueGetter: params => tooltipFormatter(params),
        autoSize: false,
    },
    {
        field: 'products_with_sales_percent',
        headerName: 'Процент товаров с продажами',
        headerTooltip: 'Процент товаров с продажами',
        sortable: true,
        filter: 'agNumberColumnFilter',
        autoSize: true,
    },
    {
        field: 'sales_per_products_avg',
        headerName: 'Среднее кол-во продаж',
        headerTooltip: 'Среднее кол-во продаж',
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'sales_per_products_with_sales_avg',
        headerName: 'Среднее кол-во товаров с продажами',
        headerTooltip: 'Среднее кол-во товаров с продажами',
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'suppliers',
        headerName: 'Продавцов',
        headerTooltip: 'Продавцов',
        sortable: true,
        autoSize: true,
    },
    {
        field: 'suppliers_with_sale',
        headerName: 'Продавцов с продажами',
        headerTooltip: 'Продавцов с продажами',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'suppliers_with_sale_percent',
        headerName: 'Процент продавцов с продажами',
        headerTooltip: 'Процент продавцов с продажами',
        sortable: true,
        filter: 'agNumberColumnFilter',
        autoSize: true,
    },
    {
        field: 'revenue_per_products_avg',
        headerName: 'Средняя выручка за 1 товар',
        headerTooltip: 'Средняя выручка за 1 товар',
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
    {
        field: 'revenue_per_products_with_sales_avg',
        headerName: 'Средняя выручка за 1 товар с продажами',
        headerTooltip: 'Средняя выручка за 1 товар с продажами',
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
];

export const sellersHeaderNames = [
    {
        field: 'supplier_name',
        headerName: 'Название',
        headerTooltip: 'Название',
        order: 0,
        sortable: true,
        filter: 'agTextColumnFilter',
        // tooltipValueGetter: params => tooltipFormatter(params),
        autoSize: false,
    },
    {
        field: 'revenue',
        headerName: 'Выручка',
        headerTooltip: 'Выручка',
        order: 1,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
    {
        field: 'avg_rating',
        headerName: 'Рейтинг',
        headerTooltip: 'Рейтинг',
        order: 2,
        sortable: true,
        filter: 'agNumberColumnFilter',
        autoSize: true,
    },
    {
        field: 'avg_comments',
        headerName: 'Комментарии',
        headerTooltip: 'Комментарии',
        order: 3,
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'products',
        headerName: 'Товаров',
        headerTooltip: 'Товаров',
        order: 4,
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'products_with_sales',
        headerName: 'Товаров с продажами',
        headerTooltip: 'Товаров с продажами',
        order: 5,
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'sales',
        headerName: 'Продажи',
        headerTooltip: 'Продажи',
        order: 6,
        comparator: sortNumValuesAgGrid,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },

    {
        field: 'graph_sales',
        headerName: 'График продаж',
        headerTooltip: 'График продаж',
        order: 7,
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
            sparklineOptions: {
                type: 'column',
                fill: colors[2],
                highlightStyle: {
                    fill: colors[2],
                },
                axis: {
                    strokeWidth: 0,
                },
            },
        },
        autoSize: false,
    },
    {
        field: 'avg_price',
        headerName: 'Средняя цена',
        headerTooltip: 'Средняя цена',
        sortable: true,
        filter: 'agNumberColumnFilter',
        comparator: sortNumValuesAgGrid,
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
    {
        field: 'products_with_sales_percent',
        headerName: 'Процент товаров с продажами',
        headerTooltip: 'Процент товаров с продажами',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        comparator: sortNumValuesAgGrid,
        autoSize: true,
    },
    {
        field: 'sales_per_products_avg',
        headerName: 'Среднее кол-во продаж',
        headerTooltip: 'Среднее кол-во продаж',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        comparator: sortNumValuesAgGrid,
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'sales_per_products_with_sales_avg',
        headerName: 'Среднее кол-во товаров с продажами',
        headerTooltip: 'Среднее кол-во товаров с продажами',
        order: 8,
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'revenue_per_products_avg',
        headerName: 'Средняя выручка за 1 товар',
        headerTooltip: 'Средняя выручка за 1 товар',
        order: 8,
        sortable: true,
        comparator: sortNumValuesAgGrid,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
    {
        field: 'revenue_per_products_with_sales_avg',
        headerName: 'Средняя выручка за 1 товар с продажами',
        headerTooltip: 'Средняя выручка за 1 товар с продажами',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        comparator: sortNumValuesAgGrid,
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
];

export const pricesHeaderNames = [
    {
        field: 'min_range',
        headerName: 'Цена от',
        headerTooltip: 'Цена от',
        width: 120,
        sortable: true,
        valueFormatter: params => currencyFormatter(params.data.min_range, '₽'),
        autoSize: false,
    },
    {
        field: 'max_range',
        headerName: 'Цена до',
        headerTooltip: 'Цена до',
        width: 120,
        sortable: true,
        valueFormatter: params => currencyFormatter(params.data.max_range, '₽'),
        autoSize: false,
    },
    {
        field: 'sales',
        headerName: 'Продажи',
        headerTooltip: 'Продажи',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.data.sales),
        autoSize: true,
    },
    {
        field: 'revenue',
        headerName: 'Выручка',
        headerTooltip: 'Выручка',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.data.revenue, '₽'),
        autoSize: true,
    },
    {
        field: 'products',
        headerName: 'Товаров',
        headerTooltip: 'Товаров',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.data.products),
        autoSize: true,
    },
    {
        field: 'products_with_sales',
        headerName: 'Товаров с продажами',
        headerTooltip: 'Товаров с продажами',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.data.products_with_sales),
        autoSize: true,
    },
    {
        field: 'suppliers',
        headerName: 'Продавцов',
        headerTooltip: 'Продавцов',
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.data.suppliers),
        autoSize: true,
    },
    {
        field: 'suppliers_with_sales',
        headerName: 'Продавцов с продажами',
        headerTooltip: 'Продавцов с продажами',
        order: 8,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.data.suppliers_with_sales),
        autoSize: true,
    },
    {
        field: 'revenue_per_products_avg',
        headerName: 'Выручка на товар',
        headerTooltip: 'Выручка на товар',
        order: 9,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.data.revenue_per_products_avg, '₽'),
        autoSize: true,
    },
    {
        field: 'revenue_per_products_with_sales_avg',
        headerName: 'Средняя цена товара с продажами',
        headerTooltip: 'Средняя цена товара с продажами',
        order: 9,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.value, '₽'),
        autoSize: true,
    },
    {
        field: 'avg_price',
        headerName: 'Средняя цена',
        headerTooltip: 'Средняя цена',
        order: 10,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => currencyFormatter(params.data.avg_price, '₽'),
        autoSize: true,
    },
    {
        field: 'sales_per_products_avg',
        headerName: 'Среднее кол-во продаж',
        headerTooltip: 'Среднее кол-во продаж',
        order: 10,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
    {
        field: 'sales_per_products_with_sales_avg',
        headerName: 'Среднее кол-во товаров с продажами',
        headerTooltip: 'Среднее кол-во товаров с продажами',
        order: 10,
        sortable: true,
        filter: 'agNumberColumnFilter',
        valueFormatter: params => numberFormatter(params.value),
        autoSize: true,
    },
];
