version: '3.8'

services:
  #PHP-FPM Service
  php-fpm:
    build:
      context: docker/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
      - ./docker/php/socket:/socket
    depends_on:
      - db-web-app
      - redis-web-app
    networks:
      - app-network

  #Nginx Service
  nginx-web-app:
    image: nginx:alpine
    restart: unless-stopped
    hostname: host.docker.internal
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .data/nginx/logs:/var/log/nginx
      - ./docker/php/socket:/socket
    depends_on:
      - php-fpm
      - db-web-app
      - redis-web-app
    ports:
      - "81:80"
      - "441:443"
    networks:
      app-network:
        aliases:
          - localhost:81
  #MySQL Service
  db-web-app:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=2M
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Europe/Moscow
    ports:
      - 3307:3306
    volumes:
      - .data/mysql-data:/var/lib/mysql
      - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  # Redis service
  redis-web-app:
    image: redis:6.2.5-alpine
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - .data/redis-data:/redis
    networks:
      - app-network

  # Laravel queue service
  queue-web-app:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/local.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db-web-app
      - redis-web-app
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cache:
  vendor:
  database:


