version: '3.8'

services:
  #PHP-FPM Service
  php-fpm:
    build:
      context: docker/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
      - ./.data/php/socket:/socket
      - .data/app/logs:/var/www/storage/logs
    depends_on:
      - redis-web-app
    networks:
      - web-app-back_app-network

  #Nginx Service
  nginx-web-app:
    build:
      context: docker/nginx
    restart: unless-stopped
    hostname: host.docker.internal
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .data/nginx/logs:/var/log/nginx
      - ./.data/php/socket:/socket
    depends_on:
      - php-fpm
      - redis-web-app
    ports:
      - 127.0.0.1:81:80
    networks:
      - web-app-back_app-network

  # Redis service
  redis-web-app:
    image: redis:6.2.5-alpine
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - .data/redis-data:/data
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-web-app:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/local.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis-web-app
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true



