version: '3.8'
services:
  #PHP-FPM Service
  php-fpm:
    build:
      context: docker/php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - .data/php/socket:/socket
      - .data/app/logs:/var/www/storage/logs
      - .data/parser:/var/parser
    depends_on:
      - db-va
      - redis-va
    networks:
      - web-app-back_app-network

  #Nginx Service
  nginx-va:
    build:
      context: docker/nginx
    restart: unless-stopped
    hostname: host.docker.internal
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./.data/nginx/logs:/var/log/nginx
      - ./.data/php/socket:/socket
    depends_on:
      - php-fpm
    ports:
      - 127.0.0.1:83:80
    networks:
      - web-app-back_app-network

  #MySQL Service
  db-va:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --innodb_buffer_pool_size=12G --innodb_buffer_pool_instances=12 --sort_buffer_size=2M --skip-log-bin
    environment:
      TZ: Europe/Moscow
    ports:
      - 127.0.0.1:3308:3306
    volumes:
      - .data/mysql-data:/var/lib/mysql
    networks:
      - web-app-back_app-network

  # Redis service
  redis-va:
    image: redis:6.2.5
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
    volumes:
      - .data/redis-data:/data
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-va:
    build: ./docker/queue
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./docker/queue/local.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db-va
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true
