version: '3.8'

services:
  #Nginx Service
  nginx-web-app:
    build:
      context: docker/nginx
    restart: unless-stopped
    hostname: host.docker.internal
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .data/nginx/logs:/var/log/nginx
    depends_on:
      - octane-web-app
    ports:
      - 127.0.0.1:81:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

  octane-web-app:
    build: docker/octane
    environment:
      DISABLE_DEFAULT_SERVER: 1
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/octane/php.ini:/usr/local/etc/php/php.ini
      - .data/app/logs:/var/www/storage/logs
    ports:
      - 8081:8081
    depends_on:
      - redis-web-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

  # Redis service
  redis-web-app:
    image: redis:6.2.5
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
    volumes:
      - .data/redis-data:/redis
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-web-app:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/php.ini:/usr/local/etc/php/php.ini
      - .data/app/logs:/var/www/storage/logs
    depends_on:
      - octane-web-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true

