version: '3.8'

services:
  # Redis service
  redis-web-app:
    image: redis:6.2.5-alpine
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - .data/redis-data:/redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  #Nginx Service
  nginx-web-app:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    hostname: host.docker.internal
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .data/nginx/logs:/var/log/nginx
    ports:
      - "81:80"
      - "441:443"
    depends_on:
      - octane-web-app
    links:
      - octane-web-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      app-network:
        aliases:
          - localhost:81

  octane-web-app:
    build: docker/octane
    environment:
      DISABLE_DEFAULT_SERVER: 1
      PHP_IDE_CONFIG: "serverName=webapp"
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=host.docker.internal remote_port=9081
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/octane/php.ini:/usr/local/etc/php/php.ini
      - ./docker/octane/docker-php-ext-yasd.ini:/usr/local/etc/php/conf.d/docker-php-ext-yasd.ini
      - .data/app/logs:/var/www/storage/logs
    ports:
      - 8081:8081
    depends_on:
      - redis-web-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  # Laravel queue service
  queue-web-app:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/php.ini:/usr/local/etc/php/php.ini
      - .data/app/logs:/var/www/storage/logs
    depends_on:
      - octane-web-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cache:
  vendor:
  database:
