<?php

namespace App\Http\Requests\Ozon;

use AnalyticPlatform\LaravelHelpers\Http\Requests\BaseRequest;

class OzonGetPlatformProductsPricesRequest extends BaseRequest
{
    protected static $RULES = [
        'query.external_id' => ['required', 'array', 'min:1', 'max:120'],
        'query.external_id.*' => [
            'integer',
            'exists:App\Models\OzProduct,external_id',
            'distinct',
        ],
    ];

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    protected static $ERROR_MESSAGES = [
        'query.products.external_id.*' => [
            'exists:App\Models\OzProduct,external_id' => 'Нет товара со значением :input поля :attribute.',
            'distinct' => 'Поле :attribute должно быть уникально.',
        ]
    ];
}
