version: '3.8'

services:
  #PHP-FPM Service
  php-fpm:
    build:
      context: docker/php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
      - ./.data/php/socket:/socket
    depends_on:
      - redis-analytics
    networks:
      - web-app-back_app-network

  #Nginx Service
  nginx-analytics:
    build:
      context: docker/nginx
    restart: unless-stopped
    hostname: host.docker.internal
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./.data/nginx/logs:/var/log/nginx
      - ./.data/php/socket:/socket
    depends_on:
      - php-fpm
    ports:
      - 127.0.0.1:85:80
    networks:
      - web-app-back_app-network

  # Redis service
  redis-analytics:
    image: redis:6.2.5
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    volumes:
      - .data/redis-data:/data
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-analytics:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./docker/queue/local.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis-analytics
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true

