version: '3.8'

services:

  #PHP-FPM Service
  php-fpm:
    build:
      context: docker/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .data/app/log:/var/log/php
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
      - ./docker/php/socket:/socket
    depends_on:
      - db-bids
    networks:
      - web-app-back_app-network

  #Nginx Service
  nginx-bids:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .data/nginx/logs:/var/log/nginx
      - ./docker/php/socket:/socket
    depends_on:
      - php-fpm
      - db-bids
    ports:
      - "82:80"
      - "442:443"
    networks:
      - web-app-back_app-network

  #MySQL Service
  db-bids:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=2M
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: Europe/Moscow
    ports:
      - "3309:3306"
    volumes:
      - .data/mysql-data:/var/lib/mysql
      - ./docker/mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-bids:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/local.ini:/usr/local/etc/php/php.ini
    depends_on:
      - php-fpm
      - db-bids
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true
volumes:
  dbdata:
    driver: local


