version: '3.8'

services:

  #PHP-FPM Service
  php-fpm:
    build:
      context: docker/php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .data/app/logs:/var/www/storage/logs
      - ./docker/php/local.ini:/usr/local/etc/php/php.ini
      - ./.data/php/socket:/socket
    networks:
      - web-app-back_app-network

  #Nginx Service
  nginx-bids:
    build: docker/nginx
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - .data/nginx/logs:/var/log/nginx
      - ./.data/php/socket:/socket
    depends_on:
      - php-fpm
    ports:
      - "82:80"
    networks:
      - web-app-back_app-network

 # Redis service
  redis-bids:
    image: redis:6.2.5
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    volumes:
      - .data/redis-data:/redis
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-bids:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/local.ini:/usr/local/etc/php/php.ini
    depends_on:
      - php-fpm
      - redis-bids
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true
