version: '3.8'

services:
  #Nginx Service
  nginx-analytics:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    hostname: host.docker.internal
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .data/nginx/logs:/var/log/nginx
    ports:
      - "85:80"
      - "446:443"
    depends_on:
      - octane-analytics
    links:
      - octane-analytics
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      web-app-back_app-network:
        aliases:
          - localhost:85

  octane-analytics:
    build: docker/octane
    environment:
      DISABLE_DEFAULT_SERVER: 1
      PHP_IDE_CONFIG: "serverName=webapp"
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=host.docker.internal remote_port=9085
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/octane/php.ini:/usr/local/etc/php/php.ini
      - ./docker/octane/docker-php-ext-yasd.ini:/usr/local/etc/php/conf.d/docker-php-ext-yasd.ini
      - .data/app/logs:/var/www/storage/logs
    ports:
      - 8085:8085
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-analytics:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    depends_on:
      - nginx-analytics
    volumes:
      - .:/var/www
      - ./docker/queue/php.ini:/usr/local/etc/php/php.ini
      - .data/app/logs:/var/www/storage/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

  redis-analytics:
    image: redis:6.2.5
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
    ports:
      - 6385:6379
    volumes:
      - .data/redis-data:/redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network


#Docker Networks
networks:
  web-app-back_app-network:
    external: true
volumes:
  dbdata:
    driver: local
  cache:
  vendor:
  database:
