version: '3.8'

services:
  #Nginx Service
  nginx-va:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    hostname: host.docker.internal
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .data/nginx/logs:/var/log/nginx
    ports:
      - "83:80"
      - "444:443"
    depends_on:
      - octane-va
    links:
      - octane-va
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      web-app-back_app-network:
        aliases:
          - localhost:83

  octane-va:
    build: docker/octane
    environment:
      DISABLE_DEFAULT_SERVER: 1
      PHP_IDE_CONFIG: "serverName=webapp"
      XDEBUG_CONFIG: idekey=PHPSTORM remote_host=host.docker.internal remote_port=9083
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/octane/php.ini:/usr/local/etc/php/php.ini
      - ./docker/octane/docker-php-ext-yasd.ini:/usr/local/etc/php/conf.d/docker-php-ext-yasd.ini
      - .data/app/logs:/var/www/storage/logs
    ports:
      - 8083:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-va:
    build: docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/php.ini:/usr/local/etc/php/php.ini
      - .data/app/logs:/var/www/storage/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true
volumes:
  dbdata:
    driver: local
  cache:
  vendor:
  database:
