version: '3.8'
services:
  #Nginx Service
  nginx-va:
    build: docker/nginx
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    volumes:
      - .:/var/www
      - .data/nginx/logs:/var/log/nginx
    depends_on:
      - octane-va
    links:
      - octane-va
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 127.0.0.1:83:80
    networks:
      - web-app-back_app-network

  octane-va:
    build: docker/octane
    environment:
      DISABLE_DEFAULT_SERVER: 1
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - .data/parser:/var/parser
      - .data/app/logs:/var/www/storage/logs
      - ./docker/octane/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8083:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

  redis-va:
    image: redis:6.2.5
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      TZ: Europe/Moscow
    restart: unless-stopped
    volumes:
      - .data/redis-data:/redis
    networks:
      - web-app-back_app-network

  # Laravel queue service
  queue-va:
    build: ./docker/queue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME:
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/queue/php.ini:/usr/local/etc/php/php.ini
      - .data/app/logs:/var/www/storage/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web-app-back_app-network

#Docker Networks
networks:
  web-app-back_app-network:
    external: true
