<?php

namespace App\Constants\Errors;

class ProductsErrors
{
    const NOT_FOR_SALE = 3000;
    const NOT_FOUND = 3001;
    const ALREADY_EXISTS = 3002;
    const CAN_NOT_UPDATE = 3003;
    const NOT_FILLED_REQUIRED_CHARACTERISTICS = 3004;
    const CHARACTERISTIC_NOT_FOUND = 3005;
    const CAN_NOT_SEND = 3006;
    const CHARACTERISTIC_OPTION_NOT_FOUND = 3007;
    const WRONG_SKU_FORMAT = 3008;
    const TOO_MANY_SKUS = 3009;
    const ALREADY_ADDED_BY_ANOTHER_USER = 3010;
    const ADDED_WITHOUT_DATA = 3011;
    const TEST_PRODUCT_LIMIT = 3012;
    const TARIFF_IS_OVER = 3013;
    const MASS_PRODUCT_ADD_IS_UNAVAILABLE = 3014;
    const EMPTY_RESULT_IN_RESPONSE = 3015;
    const NOT_FOUND_IN_OZON = 3016;
}
